import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  display: "swap",
});

const TITLE = "MinLabs — Software Studio · Mobile, Backend & AI Development";
const DESCRIPTION =
  "MinLabs is a software studio building production mobile, backend, and AI systems for startups and businesses. 9+ years of engineering experience, 20+ apps in production. Founded by Muhammad Amin.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    "MinLabs",
    "Software Studio Indonesia",
    "Software Development Studio",
    "Muhammad Amin",
    "React Native Developer",
    "Node.js Developer",
    "AI Solutions",
    "Mobile App Development",
    "Backend Development Indonesia",
    "Software Engineering Studio",
    "AgriMind",
  ],
  authors: [{ name: "MinLabs", url: "https://minlabs.id" }],
  creator: "MinLabs",
  metadataBase: new URL("https://minlabs.id"),
  alternates: { canonical: "/" },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: "website",
    url: "https://minlabs.id",
    siteName: "MinLabs",
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // Twitter image is auto-generated by app/opengraph-image.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`} suppressHydrationWarning>
      <body>
        <div style={{ overflowX: "hidden", maxWidth: "100vw", width: "100%" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
