import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
  display: "swap",
});

const TITLE = "Aminju (Muhammad Amin) — Software Engineer · Founder of MinLabs · Creator of AgriMind";
const DESCRIPTION =
  "Aminju (Muhammad Amin) — Software Engineer with 9+ years building mobile, backend, business systems, and AI solutions. Founder of MinLabs, creator of AgriMind. Available for freelance.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  keywords: [
    "Aminju",
    "Muhammad Amin",
    "Software Engineer Jakarta",
    "Founder MinLabs",
    "AgriMind",
    "Freelance Software Engineer",
    "React Native Developer",
    "Node.js Developer",
    "AI Solutions",
    "Mobile App Developer",
    "Backend Developer Indonesia",
  ],
  authors: [{ name: "Aminju (Muhammad Amin)" }],
  metadataBase: new URL("https://aminju.vercel.app"),
  alternates: { canonical: "/" },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: "website",
    url: "https://aminju.vercel.app",
    siteName: "Aminju",
    // OG image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // Twitter image is auto-generated by app/opengraph-image.tsx
  },
};

import { LanguageProvider } from "./context/LanguageContext";

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`} suppressHydrationWarning>
      <body>
        <LanguageProvider>
          <div style={{ overflowX: "hidden", maxWidth: "100vw", width: "100%" }}>
            {children}
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
